apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-kubernetes-ci-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-kubernetes-ci-cd
  template:
    metadata:
      labels:
        app: tp-kubernetes-ci-cd
    spec:
      containers:
      - name: tp-kubernetes-ci-cd
        image: crazyfranck/kubernetes-cicd-app:latest
        ports:
        - containerPort: 3000
